--Date 18 March Interview Questions Youtube:https://www.youtube.com/watch?v=FRzbOb3jdLg&list=PLavw5C92dz9Hxz0YhttDniNgKejQlPoAn
__-revision DAY1 REVISE THE cte LINKEDIN COURSE

FIND BRAND PAIR AND CREATE ID

WITH CTE AS
	(SELECT *,
	 CASE WHEN BRAND1>BRAND2 THEN CONCAT(BRAND1, BRAND2, YEAR)
		ELSE CONCAT(BRAND2, BRAND1, YEAR) END AS PAIR_ID
	FROM BRANDS),
    CTE_RN AS
    (SELECT *, ROW_NUM() OVER (PARTITION BY PAIR_ID ORDER BY PAIR_ID)
    AS RN FROM CTE)
    SELECT *
    FROM CTE_RN
    WHERE RN=1
    OR (CUSTOM1<>CUSTOM3 AND CUSTOM2<>CUSTOM4);

